trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6'
  inputs:
    packageType: sdk
    includePreviewVersions: true
    version: 6.0.100-preview.7
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './AdventOfCode.sln'
    arguments: -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: .NET Build
